services:
  server:
    build:
      context: .
    command: npm run dev
    networks:
      - expressAPI
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/app
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

networks:
  expressAPI:
    driver: bridge
