services:
  app-dev:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
  app-prod:
    build:
      context: .
      target: prod
    ports:
      - 80:3000
    environment:
      NODE_ENV: production
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    restart: unless-stopped
